# Generated by Django 3.2.8 on 2021-10-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='l_page/')),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
